---
_cert_default_certificate_path: /etc/ssl/certs/cert.crt
_cert_default_private_key_path: /etc/ssl/private/cert.key
_cert_default_csr_tmp_path: /tmp/cert.csr
_cert_default_ca_chain_path: /usr/local/share/ca-certificates/ca_chain.crt
