---
_cert_default_certificate_path: C:\Windows\Temp\cert.crt
_cert_default_private_key_path: C:\Windows\Temp\cert.key
_cert_default_csr_tmp_path: C:\Windows\Temp\cert.csr
_cert_default_ca_chain_path: C:\Windows\Temp\ca_chain.crt
