---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: testing_ca
  description: This role configures Hashicorp Vault in development mode for use in Molecule testing as a Certification Authority.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Debian
    versions:
      - bookworm
  - name: EL
    versions:
      - '9'
      - '8'
  - name: Ubuntu
    versions:
      - noble
      - jammy
      - focal

collections:
  - ansible.posix

dependencies:
  - role: trippsc2.hashi_vault.testing
