---
name: Molecule - vault_pki_role module plugin
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/module_utils/_timeparse.py
      - plugins/module_utils/_vault_module.py
      - plugins/module_utils/_vault_module_error.py
      - plugins/modules/vault_pki_role.py
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/module_utils/_timeparse.py
      - plugins/module_utils/_vault_module.py
      - plugins/module_utils/_vault_module_error.py
      - plugins/modules/vault_pki_role.py
defaults:
  run:
    working-directory: 'trippsc2.hashi_vault'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.hashi_vault'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          ansible-galaxy collection install community.docker
          molecule test -s vault_pki_role
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
